# Generated by Django 4.0.3 on 2022-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
