# Generated by Django 4.0.3 on 2022-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Markon', max_length=50, verbose_name='Brand (Default: Markon)'),
        ),
    ]
