# Generated by Django 4.0.3 on 2022-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sale (%)'),
        ),
    ]
