# Generated by Django 4.0.3 on 2022-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=False, verbose_name='Sale (%)'),
        ),
    ]
