# Generated by Django 4.0.3 on 2022-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale (%)'),
        ),
    ]
