# Generated by Django 4.0.3 on 2022-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_userproduct_image1_alter_userproduct_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='product_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='main_image',
            field=models.ImageField(upload_to='product_images/%Y/%m/%d/'),
        ),
    ]
