# Generated by Django 4.0.3 on 2022-04-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
