# Generated by Django 4.0.3 on 2022-04-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
