# Generated by Django 4.0.4 on 2022-06-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_name', models.CharField(max_length=50)),
                ('cart_number', models.IntegerField(max_length=16)),
                ('month', models.IntegerField(max_length=2)),
                ('year', models.IntegerField(max_length=4)),
                ('cvv', models.IntegerField(max_length=3)),
                ('address', models.TextField(max_length=150)),
                ('cith', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('coupon', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
