# Generated by Django 4.0.4 on 2022-06-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='year',
            field=models.IntegerField(),
        ),
    ]
