# Generated by Django 4.0.4 on 2022-06-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_checkout_cart_number_alter_checkout_cvv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='cart_name',
            new_name='cardname',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='cart_number',
            new_name='cardnumber',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='cith',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='month',
            new_name='expmonth',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='year',
            new_name='expyear',
        ),
    ]
