# Generated by Django 4.0.4 on 2022-06-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_rename_cart_name_checkout_cardname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
