# Generated by Django 4.0.4 on 2022-06-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_checkout_date_checkout_email_checkout_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='zip',
            field=models.IntegerField(default=444),
            preserve_default=False,
        ),
    ]
