# Generated by Django 4.0.4 on 2022-06-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_checkout_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='products',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
