# Generated by Django 4.0.3 on 2022-04-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_email_contact_full_name_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
